import { BpcWorkflowStepDefinition } from '../../types/bpc';

export const BPC_WORKFLOW_STEPS: BpcWorkflowStepDefinition[] = [
  {
    id: 'triagem',
    label: 'Triagem Inicial',
    category: 'Preliminar',
    description: 'Verificação prévia de enquadramento (idade 65+ ou impedimento de longo prazo PCD).',
    icon: 'rule',
  },
  {
    id: 'cadunico',
    label: 'CadÚnico & NIS',
    category: 'Preliminar',
    description: 'Conferência de inscrição e atualização nos últimos 24 meses.',
    icon: 'badge',
  },
  {
    id: 'biometria',
    label: 'Biometria (CIN / TSE)',
    category: 'Preliminar',
    description: 'Validação de cadastro biométrico conforme exigências recentes do INSS.',
    icon: 'fingerprint',
  },
  {
    id: 'composicao_familiar',
    label: 'Composição Familiar',
    category: 'Documentação & Renda',
    description: 'Mapeamento do grupo familiar que reside sob o mesmo teto (Lei 8.742/93).',
    icon: 'family_restroom',
  },
  {
    id: 'renda',
    label: 'Cálculo de Renda & Gastos',
    category: 'Documentação & Renda',
    description: 'Verificação da renda per capita (1/4 do salário mínimo) e deduções médicas/medicamentos.',
    icon: 'payments',
  },
  {
    id: 'cnis',
    label: 'Conferência de CNIS',
    category: 'Documentação & Renda',
    description: 'Análise de vínculos, remunerações e benefícios dos membros da família.',
    icon: 'receipt_long',
  },
  {
    id: 'documentos',
    label: 'Dossiê de Documentos',
    category: 'Documentação & Renda',
    description: 'Compilação de RG/CPF, certidões, comprovante de endereço e declarações.',
    icon: 'folder_shared',
  },
  {
    id: 'avaliacao_pcd',
    label: 'Laudos & PCD',
    category: 'Avaliações',
    description: 'Reunião de laudos, exames, receitas e prontuários médicos da pessoa com deficiência.',
    icon: 'medical_services',
  },
  {
    id: 'auditoria_pre_protocolo',
    label: 'Auditoria Pré-Protocolo',
    category: 'Protocolo & Acompanhamento',
    description: 'Checagem rigorosa de conformidade antes da transmissão do requerimento.',
    icon: 'fact_check',
  },
  {
    id: 'protocolo_inss',
    label: 'Protocolo Meu INSS',
    category: 'Protocolo & Acompanhamento',
    description: 'Transmissão eletrônica do requerimento com emissão de comprovante e número DER.',
    icon: 'send',
  },
  {
    id: 'acompanhamento',
    label: 'Acompanhamento do Requerimento',
    category: 'Protocolo & Acompanhamento',
    description: 'Monitoramento contínuo de status, comunicações e movimentações do INSS.',
    icon: 'sync_alt',
  },
  {
    id: 'exigencias',
    label: 'Gestão de Exigências',
    category: 'Protocolo & Acompanhamento',
    description: 'Controle de cumprimento de cartas de exigência dentro do prazo legal de 30 dias.',
    icon: 'priority_high',
  },
  {
    id: 'pericia_medica',
    label: 'Perícia Médica',
    category: 'Avaliações',
    description: 'Acompanhamento de agendamento, comparecimento e preparação para perícia do INSS.',
    icon: 'stethoscope',
  },
  {
    id: 'avaliacao_social',
    label: 'Avaliação Social',
    category: 'Avaliações',
    description: 'Acompanhamento da avaliação de serviço social e barreiras socioambientais.',
    icon: 'groups',
  },
  {
    id: 'decisao',
    label: 'Decisão Administrativa',
    category: 'Pós-Decisão',
    description: 'Análise de concessão ou indeferimento da Agência da Previdência Social.',
    icon: 'gavel',
  },
  {
    id: 'recurso',
    label: 'Recurso Administrativo (CRPS)',
    category: 'Pós-Decisão',
    description: 'Interposição de recurso ordinário junto às Juntas de Recursos da Previdência.',
    icon: 'history_edu',
  },
  {
    id: 'judicial',
    label: 'Encaminhamento Judicial',
    category: 'Pós-Decisão',
    description: 'Ação previdenciária de concessão de BPC na Justiça Federal / JEF.',
    icon: 'balance',
  },
  {
    id: 'manutencao',
    label: 'Manutenção do Benefício',
    category: 'Pós-Decisão',
    description: 'Revisão periódica (pente-fino), atualização de CadÚnico bienal e defesa.',
    icon: 'verified_user',
  },
];
